services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
    - ./frontend/views:/usr/share/nginx/html:ro
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_DB: exampledb
      POSTGRES_PASSWORD: examplepass
    volumes:
      - db-data:/var/lib/postgresql/
  
  

volumes:
  db-data: